### ISSUE TITLE
generate schema with SchemaFactory

### ISSUE THREAD

**Issue by AbdelazizSouhir** [Tony133/nestjs-api-mongoose#1]
Hi Tony,

please i use the SchemaFactory to generate my schema model but the problem that it only generates the _id on DB I can't find the whole object declared...!? please if you have any idea about that...?

thank you.

**Comment by Tony133** [comment]
Hi @AbdelazizSouhir , 

In the project I created a docker-compose, are you using that to set up a mongodb service?

I have tried it now and it generates everything

open the terminal and do this:

```cd nestjs-api-mongoose```

```docker-compose up```

open another terminal panel

```npm run start: dev```

always try to run a command curl from the terminal that are in the readme if everything works.

Tony
